[project]
name = "hydride"
version = "1.2.3"
authors = [
    {name = "The 'Hydride' contributors"},
    {name = "Jacob Anter"},
    {name = "Patrick Kunzmann"}
]
description = "Adding hydrogen atoms to molecular models"
readme = "README.rst"
requires-python = ">=3.10"
license = {file = "LICENSE.rst"}
dependencies = [
    "biotite >= 0.40",
    "numpy >= 1.25",
    "jax >= 0.4.0",
    "jaxlib",
]

[project.optional-dependencies]
test = ["pytest"]
lint = ["ruff==0.5.2"]
cuda = ["jax[cuda12]"]

[project.scripts]
hydride = "hydride.cli:main"

[build-system]
requires = [
    "setuptools >= 61.0",
    "wheel",
    "cython >= 3.0",
    "numpy >= 2.0",
    "biotite >= 1.0",
    "msgpack >= 0.5.6"
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["hydride"]

[tool.setuptools.package-data]
hydride = ["*.pickle"]

[dependency-groups]
dev = [
    "jedi>=0.19.2",
    "pytest>=9.0.3",
    "ruff>=0.5.2",
]
